feat: initial site layout
Vets-Who-Code/js-web-path-mountainmort pull request #14
Opened 2023-01-25 00:32 UTC by mountainmort

Tracking progress against Standards in #3 :

> In a Pull Request (PR) create a HTML webpage with the following:
> - [x] three different types of headings
> - [x] two paragraphs with three different kinds of inline elements
> - [x] A br and a hr
> - [x] A header and footer
> - [x] Two different sections
> - [x] An unordered list of three items
> - [x] An anchor tag with a link
> - [x] A Form with a textarea, three types of inputs` and a button
> - [x] A table with three columns and three rows with a header, body, and footer

Up next:
- Build link to additional page that contains a contact form
- Expand on content content placeholders
- Get some icons/images
- Start working on CSS Standards in #4

2023-01-28 20:10 UTC, axecopfire approved these changes

2023-01-28 20:12 UTC, axecopfire requested changes
Sorry, got excited at the deploy preview, still needs some items from the checklist

2023-01-31 15:08 UTC, mountainmort commented
@axecopfire -
Pushed up a new Contact me page and made a few tweaks that should fulfill the remaining requirements for #3.

2023-01-31 17:22 UTC, axecopfire approved these changes

2023-01-31 17:25 UTC, axecopfire commented
It looks great, you are using the `id` attribute quite a lot. The `id` is for targeting 1 single specific element on the page. You should be using `class` for things like `section-content` and `section-logo`. 
https://www.w3schools.com/html/html_classes.asp

> The value of the `id` attribute must be unique within the HTML document.
https://www.w3schools.com/html/html_id.asp

Good job on going above and beyond. The distinction will become clearer when we get to CSS.

2023-01-31 18:54 UTC, merged